services:

  app:
    container_name: webshop
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_R2DBC_URL: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_R2DBC_USERNAME: sa
      SPRING_DATASOURCE_USERNAME: sa
    ports:
      - "8888:8888"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  redis:
    image: redis:7.4.2-bookworm
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .redis_data:/data
    restart: unless-stopped