FROM amazoncorretto:21 AS build
COPY shopservice/build.gradle /app/
COPY shopservice/gradlew /app/
COPY shopservice/gradlew.bat /app/
COPY paymentservice-api.yaml /app/
COPY gradle/wrapper/gradle-wrapper.jar /app/gradle/wrapper/
COPY gradle/wrapper/gradle-wrapper.properties /app/gradle/wrapper/
COPY shopservice/src /app/src
WORKDIR /app
RUN ./gradlew clean build -x test

FROM amazoncorretto:21-al2023-headful
RUN mkdir -p /app/uploads && chmod -R 777 /app/uploads
COPY --from=build /app/build/libs/shopservice.jar /app/shopservice.jar
WORKDIR /app
EXPOSE 8888
ENV UPLOAD_DIR=/app/uploads/
ENTRYPOINT ["java", "-jar", "/app/shopservice.jar"]