server:
  port: 8888

spring:
  application:
    name: shopservice
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      key-prefix: "shop:"
      use-key-prefix: true
      time-to-live: 1h
      cache-null-values: false
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      initial-size: 5
      max-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    reactive:
      max-chunk-size: 8KB


images:
  upload-directory: ./uploads/

paymentservice-url: http://paymentservice:8889