server:
  port: 8888

spring:
  application:
    name: shopservice
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      key-prefix: "shop:"
      use-key-prefix: true
      time-to-live: 3m
      cache-null-values: false
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      initial-size: 5
      max-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    reactive:
      max-chunk-size: 8KB
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          shopservice:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: shopservice
            client-secret: secret
            scope: openid, profile, email

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

images:
  upload-directory: ./uploads/

paymentservice-url: http://localhost:8889